
L'obiettivo del progetto è apprendere mediante una rete neurale la trasformazione da punti del piano espressi in coordinate polari ad una rappresentazione basata su di una griglia discreta di dimensione 10x10, dove la cella della griglia ha valore 1 se contiene il punto, e 0 altrimenti.

Il dataset supervisionato è fornito in questo notebook nella forma di una generatore. Il generatore deve essere considerato come una "scatola nera" il cui comportamento deve essere appreso. 

Dovete progettare una rete neurale in grado di raggiungere una accuratezza del 95%. Questa è una condizione necessaria per superare l'esame, ma l'accuratezza non influisce in altro modo sulla valutazione.  

I modelli che raggiungono l'accuratezza attesa saranno invece valutati in modo inversamente proporzionale al numero dei loro parametri: **più il modello è piccolo, meglio è.**


**Attenzione**: Qualunque soluzione che tragga vantaggio, diretto o indiretto, da meta-conoscenza relativa al generatore sarà automaticamente bocciato.


In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Input, Dense, Reshape, concatenate
from tensorflow.keras.models import Model

Veniamo al generatore. Questo restituisce delle triple della forma
((theta,rho),out) dove (theta,rho) sono le coordinate polari di un punto nel primo quadrante del piano, e out è una mappa 10x10 con "1" in correspondenza alla cella che contiene il punto, e "0" altrimenti.

Settando  flat=True, la mappa 10x10 viene appiattita ad un vettore di dimensione 100. Potete utilizzare questa variante, se preferite. Nessuna altra modifica del generatore è ammessa. 

In [2]:
def polar_generator(batchsize,grid=(10,10),noise=.002,flat=False):
  while True:
    x = np.random.rand(batchsize)
    y = np.random.rand(batchsize)
    out = np.zeros((batchsize,grid[0],grid[1]))
    xc = (x*grid[0]).astype(int)
    yc = (y*grid[1]).astype(int)
    for b in range(batchsize):
      out[b,xc[b],yc[b]] = 1
    #compute rho and theta and add some noise
    rho = np.sqrt(x**2+y**2) + np.random.normal(scale=noise)
    theta = np.arctan(y/np.maximum(x,.00001)) + np.random.normal(scale=noise)
    if flat:
      out = np.reshape(out,(batchsize,grid[0]*grid[1]))
    yield ((theta,rho),out)

Creiamo una istanza del generatore con una griglia di dimensione 3x4

In [ ]:
g1,g2 = 3,4
gen = polar_generator(1,grid=(g1,g2),noise=0.0)

... e osserviamo qualche esempio

In [ ]:
(theta,rho),maps = next(gen)
for i,map in enumerate(maps):
  #let us compute the cartesian coordinates
  x = np.cos(theta[i])*rho[i]
  y = np.sin(theta[i])*rho[i]
  print("x coordinate (row): {}".format(int(x*g1)))
  print("y coordinate (col): {}".format(int(y*g2)))
  print("map:")
  print(np.reshape(map,(g1,g2)))

x coordinate (row): 1
y coordinate (col): 1
map:
[[0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]]


Utile esercizio: aggiungete rumore al generatore e verificate l'effetto sulla
"ground truth".

# Cosa consegnare

Ai fini del progetto dovete lavorare con la **griglia di default di dimensione 10x10, e con il rumore di default .002**

il generatore deve essere trattato come una scatola nera: non modificatelo e non sfruttate la sua semantica, che si suppone ignota. Potete lavorare in modlaità "flat", se preferite.

Dovete:

1.   definire una funzione per il calcolo della accuratezza (potete prendere ispirazione dal cocice della cella precedente) 
2.   definire una rete neurale che prende in input theta e rho e restituisce out
3.  misurare l'accuratezza della rete, che deve essere maggiore o uguale del 95%; l'accuratezza deve essere misurata su almeno 20000 dati
4. perfezionare il modello cercando di diminuire il più possibile il numero dei parametri mantenendo una accuratezza superiore al 95%. Solo la vostra rete migliore deve essere consegnata.

Dovete consegnare un UNICO notebook eseguibile su colab, che contenga il codice della rete, il suo sommario con il numero dei parametri, la storia di training, il codice per il calcolo della accuratezza e la sua valutazione sulla vostra rete.

**N.B.** L'accuratezza deve essere superiore o uguale a 95%, ma non influisce in altro modo sulla valutazione. Il vostro punteggio dipenderà unicamente dal numero dei parametri: più è piccolo e più la vostra vaalutazione sarà elevata.  

#Buon lavoro!





In [47]:
import keras
import numpy as np
from keras import layers
from keras import activations
from keras import losses
from sklearn.model_selection import train_test_split
import keras.backend as K

In [35]:
n_train = 100000
n_test = 20000

g1,g2 = 10,10
gen = polar_generator(n_train+n_test,grid=(g1,g2),noise=0.02,flat=True)
(theta,rho),y = next(gen)
x=np.array([i for i in zip(theta,rho)])

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=n_test/(n_train+n_test), shuffle=True, random_state=1)

In [56]:
def loss_fn(y_true, y_pred):
  point = np.array(y_true).argwhere(x==1)[1]

  x = K.mult(K.cos(y_true[:1]), y_true[:2])
  #x = np.cos(theta[i])*rho[i]
  #y = np.sin(theta[i])*rho[i]
  eval = K.sq
  eval = K.abs(y_pred - y_true)
  eval = K.mean(eval, axis=-1)

  return eval

def accuracy(true_maps: tf.Tensor, my_maps: tf.Tensor) -> float:
  return tf.math.count_nonzero(tf.math.equal(true_maps, my_maps)) / tf.cast(tf.size(true_maps), tf.int64)

def threshold(x: tf.Tensor) -> tf.Tensor:
  return K.switch(x >= 0, x*0+1, x*0)

In [60]:
model = keras.Sequential([
    layers.Flatten(),
    layers.Dense(24, activation=activations.swish),
    layers.Dense(12, activation=activations.relu),
    layers.Dense(6, activation=activations.swish),

    layers.Dense(100, activation=threshold)
])
model.build((None, 2))
model.summary()
model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=1e-3),
    loss=losses.CategoricalCrossentropy(),
    metrics=[accuracy] # ['accuracy']
)

Model: "sequential_22"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_24 (Flatten)        (None, 2)                 0         
                                                                 
 dense_98 (Dense)            (None, 24)                72        
                                                                 
 dense_99 (Dense)            (None, 12)                300       
                                                                 
 dense_100 (Dense)           (None, 6)                 78        
                                                                 
 dense_101 (Dense)           (None, 100)               700       
                                                                 
Total params: 1,150
Trainable params: 1,150
Non-trainable params: 0
_________________________________________________________________


In [61]:
batch_size = 256
history = model.fit(
    x_train,
    y_train,
    epochs=50,# 300,
    batch_size=batch_size
)

score, acc = model.evaluate(x_test, y_test,
                            batch_size=batch_size)
print('Test scire:', score)
print('Accuracy: {:.1f}%'.format(acc*100))

Epoch 1/50
391/391 [==============================] - 2s 3ms/step - loss: 9.8970 - accuracy: 0.4834
Epoch 2/50
391/391 [==============================] - 1s 3ms/step - loss: 9.8970 - accuracy: 0.4834
Epoch 3/50
391/391 [==============================] - 1s 3ms/step - loss: 9.8971 - accuracy: 0.4834
Epoch 4/50
339/391 [=========================>....] - ETA: 0s - loss: 9.8821 - accuracy: 0.4834

KeyboardInterrupt: ignored