
L'obiettivo del progetto è apprendere mediante una rete neurale la trasformazione da punti del piano espressi in coordinate polari ad una rappresentazione basata su di una griglia discreta di dimensione 10x10, dove la cella della griglia ha valore 1 se contiene il punto, e 0 altrimenti.

Il dataset supervisionato è fornito in questo notebook nella forma di una generatore. Il generatore deve essere considerato come una "scatola nera" il cui comportamento deve essere appreso. 

Dovete progettare una rete neurale in grado di raggiungere una accuratezza del 95%. Questa è una condizione necessaria per superare l'esame, ma l'accuratezza non influisce in altro modo sulla valutazione.  

I modelli che raggiungono l'accuratezza attesa saranno invece valutati in modo inversamente proporzionale al numero dei loro parametri: **più il modello è piccolo, meglio è.**


**Attenzione**: Qualunque soluzione che tragga vantaggio, diretto o indiretto, da meta-conoscenza relativa al generatore sarà automaticamente bocciato.


In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Input, Dense, Reshape, concatenate
from tensorflow.keras.models import Model

2023-01-10 13:03:56.952370: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE3 SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


Veniamo al generatore. Questo restituisce delle triple della forma
((theta,rho),out) dove (theta,rho) sono le coordinate polari di un punto nel primo quadrante del piano, e out è una mappa 10x10 con "1" in correspondenza alla cella che contiene il punto, e "0" altrimenti.

Settando  flat=True, la mappa 10x10 viene appiattita ad un vettore di dimensione 100. Potete utilizzare questa variante, se preferite. Nessuna altra modifica del generatore è ammessa. 

In [2]:
def polar_generator(batchsize,grid=(10,10),noise=.002,flat=False):
  while True:
    x = np.random.rand(batchsize)
    y = np.random.rand(batchsize)
    out = np.zeros((batchsize,grid[0],grid[1]))
    xc = (x*grid[0]).astype(int)
    yc = (y*grid[1]).astype(int)
    for b in range(batchsize):
      out[b,xc[b],yc[b]] = 1
    #compute rho and theta and add some noise
    rho = np.sqrt(x**2+y**2) + np.random.normal(scale=noise)
    theta = np.arctan(y/np.maximum(x,.00001)) + np.random.normal(scale=noise)
    if flat:
      out = np.reshape(out,(batchsize,grid[0]*grid[1]))
    yield ((theta,rho),out)

Creiamo una istanza del generatore con una griglia di dimensione 3x4

In [ ]:
g1,g2 = 3,4
gen = polar_generator(1,grid=(g1,g2),noise=0.0)

... e osserviamo qualche esempio

In [ ]:
(theta,rho),maps = next(gen)
for i,map in enumerate(maps):
  #let us compute the cartesian coordinates
  x = np.cos(theta[i])*rho[i]
  y = np.sin(theta[i])*rho[i]
  print("x coordinate (row): {}".format(int(x*g1)))
  print("y coordinate (col): {}".format(int(y*g2)))
  print("map:")
  print(np.reshape(map,(g1,g2)))

x coordinate (row): 1
y coordinate (col): 1
map:
[[0. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]]


Utile esercizio: aggiungete rumore al generatore e verificate l'effetto sulla
"ground truth".

# Cosa consegnare

Ai fini del progetto dovete lavorare con la **griglia di default di dimensione 10x10, e con il rumore di default .002**

il generatore deve essere trattato come una scatola nera: non modificatelo e non sfruttate la sua semantica, che si suppone ignota. Potete lavorare in modlaità "flat", se preferite.

Dovete:

1.   definire una funzione per il calcolo della accuratezza (potete prendere ispirazione dal cocice della cella precedente) 
2.   definire una rete neurale che prende in input theta e rho e restituisce out
3.  misurare l'accuratezza della rete, che deve essere maggiore o uguale del 95%; l'accuratezza deve essere misurata su almeno 20000 dati
4. perfezionare il modello cercando di diminuire il più possibile il numero dei parametri mantenendo una accuratezza superiore al 95%. Solo la vostra rete migliore deve essere consegnata.

Dovete consegnare un UNICO notebook eseguibile su colab, che contenga il codice della rete, il suo sommario con il numero dei parametri, la storia di training, il codice per il calcolo della accuratezza e la sua valutazione sulla vostra rete.

**N.B.** L'accuratezza deve essere superiore o uguale a 95%, ma non influisce in altro modo sulla valutazione. Il vostro punteggio dipenderà unicamente dal numero dei parametri: più è piccolo e più la vostra vaalutazione sarà elevata.  

#Buon lavoro!





In [3]:
import keras
import numpy as np
from keras import layers
from keras import activations
from keras import losses
from sklearn.model_selection import train_test_split
import keras.backend as K

size = 10

In [4]:
# def map_map(map: np.ndarray) -> np.ndarray:
#   out = np.zeros(size * 2)
#   point = np.argwhere(map==1)[0]
#   out[point[0]] = 1
#   out[size + point[1]] = 1
#   return out

def map_map(map: np.ndarray) -> np.ndarray:
  out = np.zeros(size * 2)
  point = np.argwhere(map==1)[0]
  return point

In [129]:
batch_size = 256

In [130]:
n_train = 100000
n_test = 20000

def xy(i):
  (theta,rho),y = i
  y = np.array(list(map(map_map, y)))
  x=np.array([i for i in zip(theta,rho)])
  return (x,y)

gcd = np.gcd(n_train, n_test)
gen = polar_generator(gcd,grid=(size,size),noise=0.02)

x_train, y_train = xy(next(gen))
for i in range(int(n_train/gcd)-1):
  x,y = xy(next(gen))
  x_trian = np.concatenate((x, x_train), axis=0)
  y_trian = np.concatenate((y, y_train), axis=0)

x_test, y_test = xy(next(gen))
for i in range(int(n_train/gcd)-1):
  x,y = xy(next(gen))
  x_trian = np.concatenate((x, x_test), axis=0)
  y_trian = np.concatenate((y, y_test), axis=0)

# x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=n_test/(n_train+n_test), shuffle=True, random_state=1)

In [131]:
def loss_fn(y_true, y_pred):
  point = np.array(y_true).argwhere(x==1)[1]

  x = K.mult(K.cos(y_true[:1]), y_true[:2])
  #x = np.cos(theta[i])*rho[i]
  #y = np.sin(theta[i])*rho[1,164
def my_categorical_accuracy(y_true: tf.Tensor, y_pred: tf.Tensor) -> float:
  equal = tf.equal(tf.math.argmax(y_true, 1), tf.math.argmax(y_pred , 1))
  n_correct = tf.reduce_sum(tf.cast(equal, tf.int32))
  return tf.cast(n_correct/len(y_true), tf.keras.backend.floatx())

In [158]:
model = keras.Sequential([
    layers.Flatten(),
    layers.Dense(12, activation=activations.relu),
    layers.Dense(6, activation=activations.relu),
    layers.Dense(3, activation=activations.relu),

    layers.Dense(2, activation=activations.relu)
])
model.build((None, 2))
model.summary()
model.compile(
    optimizer=keras.optimizers.SGD(learning_rate=1e-3), #Adam(learning_rate=1e-3),
    loss=losses.MeanSquaredError(),
    metrics=['accuracy']
)

Model: "sequential_23"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_23 (Flatten)        (None, 2)                 0         
                                                                 
 dense_92 (Dense)            (None, 12)                36        
                                                                 
 dense_93 (Dense)            (None, 6)                 78        
                                                                 
 dense_94 (Dense)            (None, 3)                 21        
                                                                 
 dense_95 (Dense)            (None, 2)                 8         
                                                                 
Total params: 143
Trainable params: 143
Non-trainable params: 0
_________________________________________________________________


In [159]:
history = model.fit(
    x_train,
    y_train,
    epochs=300,# 300,
    batch_size=batch_size
)

Epoch 1/300
79/79 [==============================] - 0s 1ms/step - loss: 22.2441 - accuracy: 0.4496
Epoch 2/300
79/79 [==============================] - 0s 931us/step - loss: 16.7343 - accuracy: 0.4496
Epoch 3/300
79/79 [==============================] - 0s 1ms/step - loss: 16.3879 - accuracy: 0.4496
Epoch 4/300
79/79 [==============================] - 0s 1ms/step - loss: 16.2108 - accuracy: 0.4496
Epoch 5/300
79/79 [==============================] - 0s 2ms/step - loss: 16.0396 - accuracy: 0.4496
Epoch 6/300
79/79 [==============================] - 0s 1ms/step - loss: 15.8716 - accuracy: 0.4496
Epoch 7/300
79/79 [==============================] - 0s 1ms/step - loss: 15.7055 - accuracy: 0.4496
Epoch 8/300
79/79 [==============================] - 0s 2ms/step - loss: 15.5418 - accuracy: 0.4496
Epoch 9/300
79/79 [==============================] - 0s 2ms/step - loss: 15.3829 - accuracy: 0.4496
Epoch 10/300
79/79 [==============================] - 0s 2ms/step - loss: 15.2313 - accuracy: 0.44

In [160]:
score, acc = model.evaluate(x_test, y_test,
                            batch_size=batch_size)
print(x_test.shape, y_test.shape)
print('Test score:', score)
print('Accuracy: {:.1f}%'.format(acc*100))

accs = []
for x in range(50):
  (theta,rho),y = next(gen)
  x=np.array([i for i in zip(theta,rho)])
  y = np.array(list(map(map_map, y)))

  score, acc = model.evaluate(x, y, batch_size=batch_size)
  accs.append(acc)


acc = np.mean(accs)
print('Accuracy: {:.1f}%'.format(acc*100))

79/79 [==============================] - 0s 874us/step - loss: 0.2560 - accuracy: 0.9662
(20000, 2) (20000, 2)
Test score: 0.25599074363708496
Accuracy: 96.6%
79/79 [==============================] - 0s 3ms/step - loss: 0.2888 - accuracy: 0.9634
Accuracy: 96.1%


In [168]:
x,y = xy(next(gen))
y_pred = model.predict(x[:1])
print(y[0], y_pred)

1/1 [==============================] - 0s 11ms/step
[7 0] [[6.164022 0.      ]]
